const fs=require('fs'),path=require('path'),{createRequire}=require('module');const deps=require('../browser-deps.cjs');const {chromium}=deps('playwright');
(async()=>{const browser=await chromium.launch({...(process.env.BARA_CHROME?{executablePath:process.env.BARA_CHROME}:{}),headless:true,args:['--enable-unsafe-swiftshader']});const errors=[];try{const page=await browser.newPage({viewport:{width:1440,height:1060}});page.on('pageerror',e=>{errors.push(e.message);console.log('ERROR',e.message)});const out=path.resolve('art/production/gameplay-round-01/qa');await page.addInitScript(()=>{window.audioMeters=[];const original=AudioNode.prototype.connect;AudioNode.prototype.connect=function(dest,...args){const result=original.call(this,dest,...args);if(dest instanceof AudioDestinationNode){if(!this.__baraMeter){const meter=this.context.createAnalyser();meter.fftSize=2048;const muted=this.context.createGain();muted.gain.value=0;original.call(meter,muted);original.call(muted,dest);window.audioMeters.push(meter);this.__baraMeter=meter;}original.call(this,this.__baraMeter);}return result;};});const audioEnergy=()=>page.evaluate(()=>Math.max(0,...window.audioMeters.map(m=>{const a=new Float32Array(m.fftSize);m.getFloatTimeDomainData(a);return Math.sqrt(a.reduce((s,x)=>s+x*x,0)/a.length)})));const proof={};await page.goto('http://127.0.0.1:54114/production/gameplay-round-01/?v=exploration-01');await page.waitForFunction(()=>window.baraState?.phase==='Menu',{},{timeout:90000});const state=()=>page.evaluate(()=>window.baraState);const capture=async name=>page.screenshot({path:path.join(out,name+'.png'),fullPage:true});const click=async(label,n=0)=>{const s=await state(),b=s.buttons.filter(x=>x.label===label)[n];if(!b)throw Error('Button not found '+label);const c=await page.locator('canvas').boundingBox();await page.mouse.click(c.x+(b.x+b.w/2)*c.width,c.y+(b.y+b.h/2)*c.height);await page.waitForTimeout(500)};
let layout=JSON.parse(fs.readFileSync('art/concepts/levels-round-02/levels.json'))[0],module=.92;const blocked=new Set([...layout.stations,...(layout.barriers||[])].map(s=>s.x+','+s.y));
// Barrier entries in the approved layout may span multiple cells; level one has none.
const world=(x,y)=>({x:((layout.cols-1)/2-x)*module,z:y*module});const cell=s=>({x:Math.round((layout.cols-1)/2-s.x/module),y:Math.round(s.z/module)});
const key=c=>c.x+','+c.y;const free=c=>c.x>=0&&c.x<layout.cols&&c.y>=0&&c.y<layout.rows&&!blocked.has(key(c));
function route(start,end){const queue=[start],previous=new Map([[key(start),null]]);for(let n=0;n<queue.length;n++){let c=queue[n];if(key(c)===key(end)){let result=[];while(c){result.push(c);c=previous.get(key(c))}return result.reverse();}for(const d of [[1,0],[-1,0],[0,1],[0,-1]]){let p={x:c.x+d[0],y:c.y+d[1]};if(free(p)&&!previous.has(key(p))){previous.set(key(p),c);queue.push(p)}}}return null}
function directionKeys(s,dx,dz){const right=dx*s.rightX+dz*s.rightZ,forward=dx*s.forwardX+dz*s.forwardZ;const magnitude=Math.max(Math.abs(right),Math.abs(forward));const keys=[];if(Math.abs(right)>magnitude*.42)keys.push(right>0?'d':'a');if(Math.abs(forward)>magnitude*.42)keys.push(forward>0?'w':'s');return keys;}
async function push(keys,ms){for(const key of keys)await page.keyboard.down(key);await page.waitForTimeout(ms);for(const key of keys)await page.keyboard.up(key);await page.waitForTimeout(190);}
async function travel(target){for(let i=0;i<35;i++){const s=await state(),dx=target.x-s.x,dz=target.z-s.z,distance=Math.hypot(dx,dz);if(distance<.12)return;await push(directionKeys(s,dx,dz),Math.min(140,Math.max(24,distance/3.15*730)));}throw Error('Could not reach '+JSON.stringify(target)+' '+JSON.stringify(await state()));}
async function go(id){const s=await state(),station=s.stations.find(x=>x.id===id);const goal=cell(station);const candidates=[[1,0],[-1,0],[0,1],[0,-1]].map(d=>({x:goal.x+d[0],y:goal.y+d[1]})).filter(free).map(c=>({cell:c,path:route(cell(s),c)})).filter(x=>x.path).sort((a,b)=>a.path.length-b.path.length);if(!candidates.length)throw Error('No route to '+id);for(const node of candidates[0].path)await travel(world(node.x,node.y));const here=await state();await push(directionKeys(here,station.x-here.x,station.z-here.z),55);if((await state()).focused!==id)throw Error('Did not focus '+id+' '+JSON.stringify(await state()));}
async function use(id){await go(id);await page.keyboard.press('e');await page.waitForTimeout(250);console.log('Used',id,(await state()).held)}
async function cancelByWalking(){let s=await state();await push(directionKeys(s,-s.fx,-s.fz),170);if((await state()).working)throw Error('Walking did not cancel work');}
async function chop(ingredient){await use(ingredient);await use('prep');await page.keyboard.press('Space');await page.waitForFunction(()=>window.baraState.working==='Chopping'&&window.baraState.workProgress>.12,{},{timeout:10000});if(ingredient==='tomato'){proof.chopWorking=await state();await capture('tap-chopping');await cancelByWalking();proof.chopCancelled=await state();if(proof.chopCancelled.stations.find(s=>s.id==='prep').progress<=0)throw Error('Partial chop was lost');await go('prep');await page.keyboard.press('Space');}await page.waitForFunction(()=>window.baraState.stations.find(s=>s.id==='prep').item.startsWith('Chopped'),{},{timeout:20000});await page.waitForTimeout(200);await page.keyboard.press('e');await page.waitForTimeout(250);await page.waitForFunction(()=>window.baraState.held.startsWith('Chopped'),{},{timeout:3000});}
await click('Begin service');await click('Open the cafe');await use('dishes');proof.heldPlate=await state();await use('C1');proof.counterPlate=await state();if(Math.abs(proof.heldPlate.heldScale-proof.counterPlate.stations.find(s=>s.id==='C1').scale)>.001)throw Error('Plate size changed on table');for(let i=0;i<6;i++){await page.keyboard.press('e');await page.waitForTimeout(270);}let stable=await state();if(Math.abs(stable.stations.find(s=>s.id==='C1').scale-proof.heldPlate.heldScale)>.001)throw Error('Plate scale accumulated');proof.musicEnergy=await audioEnergy();proof.music=stable;if(!stable.musicPlaying||stable.audioClips<18||proof.musicEnergy<.00001)throw Error('No audible music signal');await chop('tomato');await use('C1');await chop('cucumber');await use('C1');await use('C1');await capture('salad-ready-service-highlight');await use('serve');await page.waitForTimeout(800);let served=await state();if(served.served!==1||served.training||served.score<=0)throw Error('Delivery did not score and start service');await capture('first-order-served');console.log('REAL KEYBOARD SALAD SERVED',served.score);await page.waitForTimeout(6500);await use('return');await use('sink');await page.keyboard.press('Space');await page.waitForFunction(()=>window.baraState.workPlaying&&window.baraState.workProgress>.12,{},{timeout:10000});proof.washWorking=await state();await capture('tap-washing');await cancelByWalking();proof.washCancelled=await state();if(proof.washCancelled.workPlaying)throw Error('Wash loop did not stop on movement');await go('sink');await page.keyboard.press('Space');await page.waitForFunction(()=>window.baraState.held==='Clean dish',{},{timeout:20000});await page.waitForTimeout(200);if((await state()).held!=='Clean dish')throw Error('Washing did not return clean dish');await use('dishes');await capture('dish-cycle-complete');proof.completed=await state();if(proof.completed.guestSounds<1)throw Error('No customer reactions played');await page.keyboard.press('Escape');await page.waitForTimeout(500);proof.paused=await state();proof.pausedEnergy=await audioEnergy();if(proof.paused.musicPlaying||proof.paused.workPlaying||proof.pausedEnergy>.00001)throw Error('Audio did not pause');await page.keyboard.press('Escape');await page.waitForTimeout(500);
for(let level=2;level<=4;level++){await page.keyboard.press('Escape');await page.waitForTimeout(250);await click('Main menu');await click('Choose kitchen');await click('Enter kitchen',level-1);await capture('level-0'+level+'-briefing');await click('Open the cafe');await page.waitForTimeout(13000);await capture('level-0'+level+'-service');if((await state()).level!==level)throw Error('Wrong level loaded');}
fs.writeFileSync(path.join(out,'keyboard-playtest.json'),JSON.stringify({passed:errors.length===0,checks:['Complete salad assembled and served using real keyboard movement and interaction','Green service guidance shown','First delivery scores and starts overall timer','Customer eats and returns dirty dish','Tap starts chop/wash; release continues, walking cancels, progress is retained','Clean dish returned to finite rack','Plate scale remains fixed after repeated transfers','Music produces Web Audio signal; pause silences it; customer reactions fire','All four kitchens enter service with native UI'],proof,served,final:await state(),errors},null,2));console.log('BARA_BROWSER_SERVICE_OK');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
