from pathlib import Path
p=Path('scripts/gameplay/play_service.cjs');s=p.read_text();a=s.index('async function axis(');b=s.index('async function use(',a)
s=s[:a]+'''function directionKeys(s,dx,dz){const right=dx*s.rightX+dz*s.rightZ,forward=dx*s.forwardX+dz*s.forwardZ;const magnitude=Math.max(Math.abs(right),Math.abs(forward));const keys=[];if(Math.abs(right)>magnitude*.42)keys.push(right>0?'d':'a');if(Math.abs(forward)>magnitude*.42)keys.push(forward>0?'w':'s');return keys;}
async function push(keys,ms){for(const key of keys)await page.keyboard.down(key);await page.waitForTimeout(ms);for(const key of keys)await page.keyboard.up(key);await page.waitForTimeout(190);}
async function travel(target){for(let i=0;i<35;i++){const s=await state(),dx=target.x-s.x,dz=target.z-s.z,distance=Math.hypot(dx,dz);if(distance<.12)return;await push(directionKeys(s,dx,dz),Math.min(140,Math.max(24,distance/3.15*730)));}throw Error('Could not reach '+JSON.stringify(target)+' '+JSON.stringify(await state()));}
async function go(id){const s=await state(),station=s.stations.find(x=>x.id===id);const goal=cell(station);const candidates=[[1,0],[-1,0],[0,1],[0,-1]].map(d=>({x:goal.x+d[0],y:goal.y+d[1]})).filter(free).map(c=>({cell:c,path:route(cell(s),c)})).filter(x=>x.path).sort((a,b)=>a.path.length-b.path.length);if(!candidates.length)throw Error('No route to '+id);for(const node of candidates[0].path)await travel(world(node.x,node.y));const here=await state();await push(directionKeys(here,station.x-here.x,station.z-here.z),55);if((await state()).focused!==id)throw Error('Did not focus '+id+' '+JSON.stringify(await state()));}
''' +s[b:]
a=s.index('async function cancelByWalking(');b=s.index('async function chop(',a);s=s[:a]+'''async function cancelByWalking(){let s=await state();await push(directionKeys(s,-s.fx,-s.fz),170);if((await state()).working)throw Error('Walking did not cancel work');}
''' +s[b:]
s=s.replace("?playtest=2","?v=exploration-01");p.write_text(s)
# Reuse the actual keyboard navigator for a second recipe and free-form plating.
a=s.index("await click('Begin service');");b=s.index('}finally{',a)
scenario='''await click('Choose kitchen');await click('Enter kitchen',1);await capture('exploration-soup-guide');await click('Open the cafe');
await use('dishes');await use('C1');await use('carrot');await use('C1');await use('mushroom');await use('C1');let raw=await state();const pile=raw.stations.find(s=>s.id==='C1');if(pile.portions!==2||pile.recipe)throw Error('Raw pile was rejected or counted as a recipe');await capture('raw-food-on-plate');
await page.keyboard.press('r');await page.waitForTimeout(300);if((await state()).held!=='mushroom')throw Error('R did not lift the last raw ingredient');
async function prepareHeld(){await use('prep');await page.keyboard.press('Space');await page.waitForFunction(()=>window.baraState.stations.find(s=>s.id==='prep').item.startsWith('Chopped'),{},{timeout:20000});await page.keyboard.press('e');await page.waitForTimeout(280);}
await prepareHeld();await use('C2');await go('C1');await page.keyboard.press('r');await page.waitForTimeout(300);if((await state()).held!=='carrot')throw Error('Raw carrot could not be recovered');await prepareHeld();await use('C1');await use('C1');await use('C2');await use('C2');let chopped=await state();if(chopped.stations.find(s=>s.id==='C2').portions!==2||chopped.stations.find(s=>s.id==='C2').recipe)throw Error('Uncooked vegetables incorrectly became soup');await capture('chopped-food-stacked-on-plate');
await use('C2');await use('pot');await page.waitForTimeout(1200);const cooking=await state();if(cooking.stations.find(s=>s.kind==='pot').heat!=='Cooking'||cooking.held!=='Clean dish')throw Error('Plate ingredients did not transfer into pot');const meter=cooking.uiBoxes.find(b=>b.label.startsWith('pot-meter-'));if(!meter||meter.w>.10||meter.h>.03)throw Error('Pot meter missing or oversized');if(cooking.visibleLabels.some(t=>/COOKING|SOUP READY|New order|Salad ready|First order|Soup plated/.test(t)))throw Error('Intrusive instruction text remains');await capture('compact-pot-progress');await page.waitForFunction(()=>window.baraState.stations.find(s=>s.kind==='pot').heat==='Ready',{},{timeout:22000});await page.keyboard.press('e');await page.waitForTimeout(350);if((await state()).held!=='Woodland soup')throw Error('Soup did not plate');await use('serve');await page.waitForTimeout(400);const served=await state();if(served.served!==1)throw Error('Valid soup did not serve');await capture('quiet-soup-delivery');
fs.writeFileSync(path.join(out,'exploration-playtest.json'),JSON.stringify({passed:true,checks:['Whole vegetables can be plated without making a dish','R recovers the original ingredient','Chopped carrot and mushroom remain an uncooked pile on a plate','A plate can transfer both ingredients into the pot','Pot uses a small world progress meter without text','Correctly cooked soup can be served','Routine tutorial text is absent from play'],raw,chopped,cooking,served,errors},null,2));console.log('BARA_EXPLORATION_BROWSER_OK');
'''
s=s[:a]+scenario+s[b:];s=s.replace("levels.json'))[0]","levels.json'))[1]");Path('scripts/gameplay/play_exploration.cjs').write_text(s)
