"""Four different route problems, one common counter and dish system."""
def s(id,kind,x,y,face='S'):
    return dict(id=id,kind=kind,x=x,y=y,face=face)
def c(n,x,y):return s(f'C{n}','counter',x,y)

LEVELS=[
 dict(id=1,title='First Service',shape='Open U',subtitle='Learn to assemble food anywhere on a free worktop.',cols=8,rows=7,
      ingredients=['tomato','cucumber'],recipes=['salad'],skill='Pick up, chop, combine, serve and wash',start=[4,4],dish_pool=3,tickets=1,
      stations=[s('tomato','tomato',1,0),s('cucumber','cucumber',2,0),s('prep','prep',3,0),c(1,4,0),c(2,5,0),
                c(3,0,0),s('dishes','dishes',0,2,'E'),c(4,0,3),s('sink','sink',0,4,'E'),s('return','return',0,5,'E'),
                c(5,7,1),c(6,7,2),s('serve','serve',7,3,'W'),s('bin','bin',7,5,'W')],
      barriers=[],dash=None,throws=[],
      routes=[dict(kind='food',ids=['tomato','prep','C1','serve']),dict(kind='wash',ids=['return','sink','dishes'])],
      headline='A short U around an open working area. Six interchangeable empty counters.',
      decision='Choose a counter for the current dish and another for the next chopped ingredient.',
      loop='Put a clean dish on any empty counter. Add chopped tomato and cucumber in either order, then serve. The second ingredient needs its own pickup and chop.',
      changed='No island or divided route. The first level teaches the common counter system with several convenient assembly positions.',
      counter_groups=['C1–C2: beside chopping','C3–C4: dish and washing side','C5–C6: near serving'],
      fairness='Guide the first complete serve-and-wash loop without order pressure. All six empty worktops behave identically.'),
 dict(id=2,title='Around the Island',shape='Ring route',subtitle='Prepare on the far side; cook and serve on the near side.',cols=9,rows=9,
      ingredients=['carrot','mushroom'],recipes=['soup'],skill='Cooking and dash',start=[1,6],dish_pool=3,tickets=2,
      stations=[s('carrot','carrot',2,0),s('mushroom','mushroom',6,0),
                s('prep','prep',3,3,'N'),c(1,4,3),c(2,5,3),c(3,3,4),c(4,5,4),c(5,3,5),s('pot','pot',4,5),c(6,5,5),
                s('return','return',1,8,'N'),s('sink','sink',2,8,'N'),s('dishes','dishes',3,8,'N'),c(7,5,8),s('serve','serve',6,8,'N'),c(8,7,8),s('bin','bin',8,8,'N')],
      barriers=[dict(kind='solid',cells=[[4,4]])],dash=[[1,2],[1,5]],throws=[],
      routes=[dict(kind='food',ids=['carrot','prep','pot','serve']),dict(kind='wash',ids=['return','sink','dishes'])],
      headline='One central block creates a loop, with preparation and cooking on opposite faces.',
      decision='Walk around the left or right end, and decide whether the cooking window is long enough for another preparation trip.',
      loop='Chop carrot and mushroom, then add both to the pot. While they cook, wash or stage the next ingredient. Fill a clean universal dish at the ready pot and serve.',
      changed='The island interrupts the direct route. The player circulates around it instead of crossing an open room; eight free counters support advance preparation.',
      counter_groups=['C1–C2: raw or chopped preparation buffers','C3–C6: flexible worktops on both island sides','C7–C8: clean dishes or finished orders near serving'],
      fairness='Teach cooking before introducing a second ticket. Keep the pot status visible. Dash helps on the clear side aisle; tune completion for walking first.'),
 dict(id=3,title='Across the Divide',shape='Two areas · one passage',subtitle='Throw food across the rail; walk around to use it.',cols=11,rows=9,
      ingredients=['tomato','cucumber','carrot','mushroom'],recipes=['salad','soup'],skill='Ingredient throw',start=[1,6],dish_pool=4,tickets=2,
      stations=[s('tomato','tomato',2,0),s('cucumber','cucumber',3,0),c(1,4,0),c(2,5,0),s('carrot','carrot',6,0),s('mushroom','mushroom',7,0),s('prep','prep',8,0),c(3,9,0),
                c(4,4,5),c(5,5,5),c(6,7,5),c(7,8,5),s('pot','pot',10,6,'W'),c(8,8,7),
                s('return','return',2,8,'N'),s('sink','sink',3,8,'N'),s('dishes','dishes',4,8,'N'),s('serve','serve',7,8,'N'),s('bin','bin',10,8,'N')],
      barriers=[dict(kind='rail',cells=[[x,4] for x in range(2,11)])],dash=[[1,2],[1,6]],
      throws=[dict(start=[4,3],target='C4'),dict(start=[5,3],target='C5'),dict(start=[7,3],target='C6'),dict(start=[8,3],target='C7')],
      routes=[dict(kind='food',ids=['tomato','prep','C4','serve']),dict(kind='soup',ids=['carrot','prep','pot','serve']),dict(kind='wash',ids=['return','sink','dishes'])],
      headline='A low rail separates preparation from service. The only walking connection is the two-module passage on the left.',
      decision='Stage both chopped ingredients over the rail before walking to the other side once.',
      loop='Prepare on the upper side. Throw ingredients onto ordinary empty counters below, then go around the rail to plate a salad or load the soup pot. Return to preparation while keeping space free below.',
      changed='The barrier cannot be walked through or used as a counter. Food takes a short airborne route; the chef takes a longer passage route. No dedicated landing or salad station.',
      counter_groups=['C1–C3: preparation-side buffers','C4–C7: four flexible counters beyond the rail','C8: spare counter by cooking and service'],
      fairness='Teach one throw with pressure paused. Then practice two ingredients into two empty counters. An occupied target keeps the item in hand. Every station still has a walking route.'),
 dict(id=4,title='The Zigzag Café',shape='Three areas · offset passages',subtitle='Pantry → preparation → cooking and service.',cols=14,rows=9,
      ingredients=['tomato','cucumber','carrot','mushroom'],recipes=['salad','soup'],skill='Batch preparation, dash and two throw shortcuts',start=[11,6],dish_pool=5,tickets=3,
      stations=[s('tomato','tomato',0,0),s('cucumber','cucumber',1,0),s('carrot','carrot',2,0),s('mushroom','mushroom',3,0),
                c(1,0,3),c(2,0,4),c(3,1,8),c(4,2,8),
                c(5,5,2),c(6,5,3),c(7,5,5),c(8,8,6),c(9,7,0),s('prep','prep',6,8,'N'),s('prep2','prep',7,8,'N'),
                c(10,10,4),c(11,10,5),c(12,12,0),c(13,13,5),s('pot','pot',13,3,'W'),s('serve','serve',13,7,'W'),
                s('dishes','dishes',10,8,'N'),s('sink','sink',11,8,'N'),s('return','return',12,8,'N'),s('bin','bin',13,0)],
      barriers=[dict(kind='rail',cells=[[4,y] for y in range(7)]),dict(kind='rail',cells=[[9,y] for y in range(2,9)])],
      dash=[[6,2],[6,6]],throws=[dict(start=[3,2],target='C5'),dict(start=[3,3],target='C6'),dict(start=[8,4],target='C10'),dict(start=[8,5],target='C11')],
      routes=[dict(kind='food',ids=['tomato','prep','C10','serve']),dict(kind='soup',ids=['carrot','prep','pot','serve']),dict(kind='wash',ids=['return','sink','dishes'])],
      headline='Three work areas connect at alternating ends: bottom passage first, top passage second. Throws cut across both low rails.',
      decision='Send a small batch of raw ingredients to preparation, process it, then send chopped ingredients to service before moving on.',
      loop='Pantry on the left, chopping in the middle, cooking/assembly/serving on the right. Keep the dish pool on the service side. Reserve some counters for clean dishes instead of filling every surface with ingredients.',
      changed='A three-stage zigzag replaces level 3’s single crossing. The second ingredient-transfer step and shared counter space create a new planning problem without adding recipes.',
      counter_groups=['C1–C4: pantry-side staging','C5–C9: preparation buffers','C10–C13: cooking, assembly and ready dishes'],
      fairness='Start with one calm ticket; allow three only after tuning. Test the full dish cycle at walking speed. Barriers stay fixed, passages never close, and a helper is not required.')
]
