using UnityEngine;
using UnityEngine.UIElements;
namespace BaraKitchen.Gameplay {
    // Small resolution-independent illustrations drawn in the native game UI.
    public sealed class KitchenMotif : VisualElement {
        public enum Shape { Wood, Leaves, Clip, Coin, Clock, Star, Paw, Arrow, Check, Flame, Ticket, Move, Dash, Throw, Bin }
        public Shape symbol; Shape shape=>symbol; public float amount=1;
        static readonly Color Bark=new Color(.38f,.25f,.16f), Honey=new Color(.78f,.55f,.30f), Cream=new Color(1,.96f,.81f), Green=new Color(.32f,.49f,.35f);
        public KitchenMotif(Shape value){symbol=value;pickingMode=PickingMode.Ignore;generateVisualContent+=Draw;}
        static void Circle(Painter2D p,Vector2 c,float r,Color fill){p.fillColor=fill;p.BeginPath();p.Arc(c,r,0,360);p.ClosePath();p.Fill();}
        static void Line(Painter2D p,Vector2 a,Vector2 b,Color color,float width){p.strokeColor=color;p.lineWidth=width;p.BeginPath();p.MoveTo(a);p.LineTo(b);p.Stroke();}
        static void Paw(Painter2D p,Vector2 c,float s,Color color){Circle(p,c+new Vector2(0,s*.21f),s*.30f,color);for(int i=0;i<3;i++)Circle(p,c+new Vector2((i-1)*s*.30f,-s*.21f-Mathf.Sin(i*Mathf.PI/2)*s*.1f),s*.14f,color);}
        void Draw(MeshGenerationContext ctx){var p=ctx.painter2D;float w=contentRect.width,h=contentRect.height;if(w<1||h<1)return;var c=new Vector2(w/2,h/2);float r=Mathf.Min(w,h)/2-4;
            if(shape==Shape.Arrow){Line(p,new Vector2(4,c.y),new Vector2(w-5,c.y),Green,3);Line(p,new Vector2(w-12,c.y-6),new Vector2(w-5,c.y),Green,3);Line(p,new Vector2(w-12,c.y+6),new Vector2(w-5,c.y),Green,3);}
            else if(shape==Shape.Check){Line(p,new Vector2(w*.15f,h*.52f),new Vector2(w*.40f,h*.78f),Green,3);Line(p,new Vector2(w*.40f,h*.78f),new Vector2(w*.88f,h*.20f),Green,3);}
            else if(shape==Shape.Bin){Line(p,new Vector2(w*.2f,h*.25f),new Vector2(w*.8f,h*.25f),Bark,3);Line(p,new Vector2(w*.4f,h*.1f),new Vector2(w*.6f,h*.1f),Bark,3);p.strokeColor=Bark;p.lineWidth=3;p.BeginPath();p.MoveTo(new Vector2(w*.25f,h*.3f));p.LineTo(new Vector2(w*.3f,h*.9f));p.LineTo(new Vector2(w*.7f,h*.9f));p.LineTo(new Vector2(w*.75f,h*.3f));p.Stroke();Line(p,new Vector2(w*.43f,h*.4f),new Vector2(w*.43f,h*.78f),Bark,2);Line(p,new Vector2(w*.57f,h*.4f),new Vector2(w*.57f,h*.78f),Bark,2);}
            else if(shape==Shape.Flame){p.fillColor=new Color(.94f,.43f,.16f);p.BeginPath();p.MoveTo(new Vector2(w*.5f,1));p.BezierCurveTo(new Vector2(w*.35f,h*.48f),new Vector2(w*.12f,h*.34f),new Vector2(w*.13f,h*.66f));p.BezierCurveTo(new Vector2(w*.1f,h),new Vector2(w*.88f,h),new Vector2(w*.88f,h*.6f));p.BezierCurveTo(new Vector2(w*.82f,h*.3f),new Vector2(w*.64f,h*.42f),new Vector2(w*.5f,1));p.Fill();}
            else if(shape==Shape.Ticket){p.fillColor=Cream;p.strokeColor=Honey;p.lineWidth=3;p.BeginPath();p.MoveTo(new Vector2(5,5));p.LineTo(new Vector2(w-5,5));p.LineTo(new Vector2(w-5,h-5));p.LineTo(new Vector2(5,h-5));p.ClosePath();p.Fill();p.Stroke();Paw(p,new Vector2(c.x,h*.36f),w*.35f,Green);Line(p,new Vector2(12,h*.70f),new Vector2(w-12,h*.70f),Green,5);}
            else if(shape==Shape.Move){Paw(p,c,r*.55f,Green);foreach(var d in new[]{Vector2.up,Vector2.down,Vector2.left,Vector2.right}){var tip=c+d*r;Line(p,c+d*r*.62f,tip,Green,3);var n=new Vector2(-d.y,d.x);Line(p,tip,tip-d*5+n*4,Green,2);Line(p,tip,tip-d*5-n*4,Green,2);}}
            else if(shape==Shape.Dash){Paw(p,new Vector2(w*.72f,h*.48f),r*.8f,Green);for(int i=0;i<3;i++)Line(p,new Vector2(w*.1f,h*(.30f+i*.18f)),new Vector2(w*.45f,h*(.30f+i*.18f)),Honey,3);}
            else if(shape==Shape.Throw){Line(p,new Vector2(w*.44f,h*.5f),new Vector2(w*.44f,h*.9f),Honey,5);Line(p,new Vector2(w*.60f,h*.5f),new Vector2(w*.60f,h*.9f),Honey,5);Line(p,new Vector2(w*.38f,h*.60f),new Vector2(w*.67f,h*.60f),Honey,4);p.strokeColor=Green;p.lineWidth=3;p.BeginPath();p.MoveTo(new Vector2(w*.1f,h*.62f));p.BezierCurveTo(new Vector2(w*.2f,-h*.1f),new Vector2(w*.8f,-h*.1f),new Vector2(w*.9f,h*.57f));p.Stroke();Circle(p,new Vector2(w*.89f,h*.58f),5,new Color(.9f,.3f,.18f));}
            else if(shape==Shape.Wood){p.fillColor=Honey;p.strokeColor=Bark;p.lineWidth=4;p.BeginPath();p.MoveTo(new Vector2(12,3));p.LineTo(new Vector2(w-12,3));p.QuadraticCurveTo(new Vector2(w-3,3),new Vector2(w-3,15));p.LineTo(new Vector2(w-3,h-16));p.QuadraticCurveTo(new Vector2(w-3,h-3),new Vector2(w-16,h-3));p.LineTo(new Vector2(12,h-3));p.QuadraticCurveTo(new Vector2(3,h-3),new Vector2(3,h-15));p.LineTo(new Vector2(3,16));p.QuadraticCurveTo(new Vector2(3,3),new Vector2(12,3));p.ClosePath();p.Fill();p.Stroke();for(float y=50;y<h-20;y+=55){Line(p,new Vector2(8,y),new Vector2(w-8,y+2),new Color(.48f,.31f,.18f,.3f),2);Line(p,new Vector2(22,y-12),new Vector2(w*.42f,y-11),new Color(.97f,.76f,.46f,.38f),2);}foreach(float x in new[]{14f,w-14})foreach(float y in new[]{16f,h-16})Circle(p,new Vector2(x,y),2.8f,Bark);}
            else if(shape==Shape.Clip){Line(p,new Vector2(c.x,0),new Vector2(c.x,h),Honey,14);Line(p,new Vector2(c.x-2,0),new Vector2(c.x-2,h),Cream,2);Circle(p,c,3,Bark);}
            else if(shape==Shape.Coin){Circle(p,c,r,Bark);Circle(p,c+Vector2.up*-2,r-3,new Color(.97f,.71f,.22f));Circle(p,c,r-8,new Color(1,.82f,.34f));Paw(p,c,r*.86f,new Color(.69f,.43f,.12f));}
            else if(shape==Shape.Paw){Paw(p,c,r,Green);}
            else if(shape==Shape.Star){p.fillColor=amount>0?new Color(1,.76f,.27f):new Color(.83f,.81f,.66f);p.strokeColor=amount>0?new Color(.64f,.39f,.14f):new Color(.59f,.59f,.46f);p.lineWidth=2;p.BeginPath();for(int i=0;i<10;i++){float a=-Mathf.PI/2+i*Mathf.PI/5;var q=c+new Vector2(Mathf.Cos(a),Mathf.Sin(a))*r*(i%2==0?1:.46f);if(i==0)p.MoveTo(q);else p.LineTo(q);}p.ClosePath();p.Fill();p.Stroke();}
            else if(shape==Shape.Clock&&r<24){Circle(p,c,r,Bark);Circle(p,c,r-2,Cream);Line(p,c,c+new Vector2(0,-r*.58f),Green,2);Line(p,c,c+new Vector2(r*.45f,r*.23f),Green,2);Circle(p,c,1.5f,Bark);}
            else if(shape==Shape.Clock){Circle(p,c+Vector2.down*2,r,Bark);Circle(p,c,r-4,Honey);Circle(p,c,r-10,Cream);p.strokeColor=amount<.12f?new Color(.83f,.32f,.24f):Green;p.lineWidth=6;p.BeginPath();p.Arc(c,r-15,-90,-90+Mathf.Clamp01(amount)*359.9f);p.Stroke();for(int i=0;i<12;i++){float a=i*Mathf.PI/6;var d=new Vector2(Mathf.Cos(a),Mathf.Sin(a));Line(p,c+d*(r-23),c+d*(r-20),Bark,2);}}
            else if(shape==Shape.Leaves){Line(p,new Vector2(w*.48f,h),new Vector2(w*.56f,0),Green,3);for(int i=0;i<5;i++){float y=h*.13f+i*h*.17f;float x=w*(i%2==0?.50f:.55f);float dir=i%2==0?-1:1;p.fillColor=i%2==0?Green:new Color(.52f,.65f,.38f);p.BeginPath();p.MoveTo(new Vector2(x,y+19));p.BezierCurveTo(new Vector2(x+dir*w*.54f,y+14),new Vector2(x+dir*w*.40f,y-20),new Vector2(x+dir*w*.37f,y-25));p.BezierCurveTo(new Vector2(x+dir*w*.08f,y-26),new Vector2(x+dir*w*.02f,y+3),new Vector2(x,y+19));p.ClosePath();p.Fill();}Circle(p,new Vector2(w*.52f,h*.36f),5,new Color(.95f,.64f,.30f));}
        }
    }
}
